# 专门写配置文件的语言
publish:
    - app:
        name: 微信
        date: 20200218
        versions: 1.0
    - app:
        name: 支付宝
        date: 20200218
        versions: 1.0
    - app:
          name: 精品段子
          date: 20200224
          versions: 1.0
    - app:
        name: 新闻头条
        date: 20200224
        versions: 1.0

develope:
    - app: ~


